version: '3'
services:
  app:
    build:
      context: app
      dockerfile: docker/app.Dockerfile
    container_name: pleez_reactjs
    ports:
      - 80:3000
    volumes:
      - ~/Desktop/pleez/app:/var/www/html/app
    depends_on:
      - api
  api:
    build:
      context: api
      dockerfile: docker/api.Dockerfile
    container_name: pleez_nodejs
    ports:
      - 3333:3333
    volumes:
      - ~/Desktop/pleez/api:/var/www/html/api
    links:
      - postgresql
  postgresql:
    image: postgres:9.4
    container_name: pleez_db_pg
    ports:
      - 5432:5432
    volumes:
      - ~/Desktop/pleez/database:/data/db
    environment: 
      - POSTGRES_DB=pleez
      - POSTGRES_USER=pleez
      - POSTGRES_PASSWORD=pleez
