version: '3'
services:
  app:
    build:
      context: app
      dockerfile: app.Dockerfile
    container_name: pleez_reactjs
    ports:
      - 80:3000
    volumes:
      - ./app:/usr/app
    depends_on:
      - api
  restaurant-app:
    build:
      context: restaurant-app
      dockerfile: restaurant-app.Dockerfile
    container_name: pleez_restaurant_app
    ports:
      - 3000:3000
    volumes:
      - ./restaurant-app:/usr/app
    stdin_open: true
  api:
    build:
      context: api
      dockerfile: api.Dockerfile
    container_name: pleez_nodejs
    ports:
      - 3333:3333
    volumes:
      - ./api:/usr/app
    links:
      - postgresql
    depends_on:
      - mongodb
      - postgresql
  postgresql:
    image: postgres:9.4
    container_name: pleez_db_pg
    ports:
      - 5432:5432
    volumes:
      - ./database/postgresql:/data/db
    environment: 
      - POSTGRES_DB=pleez
      - POSTGRES_USER=pleez
      - POSTGRES_PASSWORD=pleez
  mongodb:
    image: mongo:latest
    container_name: pleez_db_mongo
    ports:
      - 27017:27017
    volumes:
      - ./database/mongodb:/data/db
    environment: 
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
